package combinaciones;

import java.io.IOException;
import java.nio.file.Files;
import java.rmi.Naming;
import java.util.ArrayList;
import java.util.stream.Stream;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import servidor.ServidorInterfaz;

public class FrmCombinaciones extends javax.swing.JFrame {

    /**
     * Creates new form FrmCombinaciones
     */
    public FrmCombinaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumeros = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnArchivo = new javax.swing.JButton();
        btnSecuencial = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCombinaciones = new javax.swing.JTextArea();
        txtTiempoSec = new javax.swing.JLabel();
        btnConcurrente = new javax.swing.JButton();
        txtTiempoConc = new javax.swing.JLabel();
        numBuscado = new javax.swing.JSpinner();
        btnParalelo = new javax.swing.JButton();
        txtTiempoParalelo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtServidor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Combinaciones");

        txtNumeros.setText("1, 2, 3, 4");

        jLabel1.setText("Números");

        jLabel2.setText("Buscado");

        btnArchivo.setText("Archivo");
        btnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoActionPerformed(evt);
            }
        });

        btnSecuencial.setText("Secuencial");
        btnSecuencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecuencialActionPerformed(evt);
            }
        });

        txtCombinaciones.setColumns(20);
        txtCombinaciones.setRows(5);
        jScrollPane1.setViewportView(txtCombinaciones);

        txtTiempoSec.setText("Tiempo:");

        btnConcurrente.setText("Concurrente");
        btnConcurrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcurrenteActionPerformed(evt);
            }
        });

        txtTiempoConc.setText("Tiempo:");

        numBuscado.setModel(new javax.swing.SpinnerNumberModel(5, null, null, 1));

        btnParalelo.setText("Paralelo");
        btnParalelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParaleloActionPerformed(evt);
            }
        });

        txtTiempoParalelo.setText("Tiempo:");

        jLabel3.setText("Servidor:");

        txtServidor.setText("172.20.10.10:1234");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumeros)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnArchivo))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSecuencial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTiempoSec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConcurrente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTiempoConc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnParalelo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTiempoParalelo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnArchivo)
                    .addComponent(numBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSecuencial)
                    .addComponent(txtTiempoSec)
                    .addComponent(btnConcurrente)
                    .addComponent(txtTiempoConc)
                    .addComponent(btnParalelo)
                    .addComponent(txtTiempoParalelo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoActionPerformed
        
        JFileChooser escogerArchivo = new JFileChooser(".");
        if(escogerArchivo.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;
        try {
            txtNumeros.setText(
                Files.lines(escogerArchivo.getSelectedFile().toPath())
                    .reduce("", (a, b) -> a + ", " + b).substring(2)
            );
        } catch(IOException ex) { }
    }//GEN-LAST:event_btnArchivoActionPerformed

    private void mostrarResultado(int modo) {
        
        JLabel etiqueta = modo == CONCURRENTE ? txtTiempoConc :
            modo == SECUENCIAL ? txtTiempoSec : txtTiempoParalelo;
        int[] numeros = Stream.of(txtNumeros.getText().split(",\\s*"))
            .mapToInt(Integer::parseInt).toArray();
        int buscado = (int)numBuscado.getValue();
        
        etiqueta.setText("Calculando...");
        long t1 = System.nanoTime();
        ArrayList<ArrayList<Integer>> combinaciones = modo == CONCURRENTE ?
            Combinaciones.combinacionesConcurrente(numeros, buscado) : modo == SECUENCIAL ?
            Combinaciones.combinaciones(numeros, buscado) :
            Combinaciones.combinacionesParalelo(numeros, buscado, servidor);
        long t2 = System.nanoTime();
        
        etiqueta.setText((t2 - t1) / 1e+6 + "ms");
        txtCombinaciones.setText(
            combinaciones.stream().map(Object::toString)
                .reduce("", (r, s) -> r + s + '\n')
        );
    }
    
    ServidorInterfaz servidor;
    public static int SECUENCIAL = 1;
    public static int CONCURRENTE = 2;
    public static int PARALELO = 3;
    
    private void btnSecuencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecuencialActionPerformed
        mostrarResultado(SECUENCIAL);
    }//GEN-LAST:event_btnSecuencialActionPerformed

    private void btnConcurrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcurrenteActionPerformed
        mostrarResultado(CONCURRENTE);
    }//GEN-LAST:event_btnConcurrenteActionPerformed

    private void btnParaleloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParaleloActionPerformed
        try {
            servidor = (ServidorInterfaz)Naming.lookup("//" + txtServidor.getText() + "/Combinaciones");
            mostrarResultado(PARALELO);
        } catch(Exception ex) {
            txtCombinaciones.setText(ex.getMessage());
        }
    }//GEN-LAST:event_btnParaleloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCombinaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCombinaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCombinaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCombinaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCombinaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArchivo;
    private javax.swing.JButton btnConcurrente;
    private javax.swing.JButton btnParalelo;
    private javax.swing.JButton btnSecuencial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner numBuscado;
    private javax.swing.JTextArea txtCombinaciones;
    private javax.swing.JTextField txtNumeros;
    private javax.swing.JTextField txtServidor;
    private javax.swing.JLabel txtTiempoConc;
    private javax.swing.JLabel txtTiempoParalelo;
    private javax.swing.JLabel txtTiempoSec;
    // End of variables declaration//GEN-END:variables
}
